# Generated by Django 4.1 on 2022-08-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_quickbooks', '0004_auto_20200122_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='realm',
            name='last_updated_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='realm',
            name='token',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
