# Generated by Django 4.1 on 2022-08-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_quickbooks', '0005_realm_last_updated_at_realm_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realm',
            name='last_updated_at',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
