# Generated by Django 4.1 on 2022-08-27 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_quickbooks', '0006_alter_realm_last_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realm',
            name='schema_name',
            field=models.CharField(max_length=100),
        ),
    ]
