# Generated by Django 4.1 on 2022-08-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quickbooks_identifier', models.BigIntegerField()),
                ('name', models.CharField(default='', max_length=100)),
                ('workspace_id', models.IntegerField()),
                ('address1', models.CharField(default='', max_length=50)),
                ('address2', models.CharField(default='', max_length=50)),
                ('city', models.CharField(default='', max_length=50)),
                ('state', models.CharField(default='', max_length=5)),
                ('zip', models.CharField(default='', max_length=10)),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(default='', max_length=50)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
