# Generated by Django 4.1 on 2022-08-22 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexulquickbook', '0003_alter_customer_first_name_alter_customer_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qbd_object_id', models.CharField(editable=False, max_length=127, null=True, unique=True)),
                ('qbd_object_updated_at', models.DateTimeField(editable=False, null=True)),
                ('qbd_object_version', models.CharField(editable=False, max_length=127, null=True)),
                ('quickbooks_identifier', models.BigIntegerField()),
                ('company_id', models.IntegerField()),
                ('workspace_id', models.IntegerField()),
                ('name', models.CharField(default='', max_length=100)),
                ('address1', models.CharField(default='', max_length=50)),
                ('address2', models.CharField(default='', max_length=50, null=True)),
                ('city', models.CharField(default='', max_length=50)),
                ('state', models.CharField(default='', max_length=5)),
                ('zip', models.CharField(default='', max_length=10)),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('phone', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('notes', models.CharField(default='', max_length=50, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qbd_object_id', models.CharField(editable=False, max_length=127, null=True, unique=True)),
                ('qbd_object_updated_at', models.DateTimeField(editable=False, null=True)),
                ('qbd_object_version', models.CharField(editable=False, max_length=127, null=True)),
                ('quickbooks_identifier', models.BigIntegerField()),
                ('workspace_id', models.IntegerField()),
                ('name', models.CharField(default='', max_length=100)),
                ('part_number', models.CharField(default='', max_length=100)),
                ('label', models.CharField(default='', max_length=100)),
                ('plural_label', models.CharField(default='', max_length=100)),
                ('type', models.CharField(default='', max_length=50)),
                ('cost', models.IntegerField()),
                ('category_id', models.IntegerField()),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('notes', models.CharField(default='', max_length=50, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='customer',
            name='address2',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='notes',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
