# Generated by Django 4.1 on 2022-08-22 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexulquickbook', '0004_assets_items_alter_customer_address2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qwc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(default='', max_length=50)),
                ('app_id', models.CharField(default='', max_length=10)),
                ('app_url', models.CharField(default='', max_length=100)),
                ('app_description', models.TextField(default='')),
                ('username', models.CharField(default='', max_length=20)),
                ('owner_id', models.CharField(default='', max_length=100)),
                ('file_id', models.CharField(default='', max_length=100)),
                ('qbtype', models.CharField(choices=[('QBFS', 'Qbfs'), ('QBPOS', 'Qbpos')], default='QBFS', max_length=10)),
                ('run_every_minutes', models.IntegerField(default=5)),
            ],
        ),
    ]
