# Generated by Django 4.1 on 2022-08-22 05:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lexulquickbook', '0005_qwc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qwc',
            name='file_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='qwc',
            name='owner_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='qwc',
            name='run_every_minutes',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
