# Generated by Django 4.1 on 2022-08-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexulquickbook', '0006_alter_qwc_file_id_alter_qwc_owner_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qwc',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
